#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <avr/io.h>
#include <string.h>
#include <avr/interrupt.h>
#include <avr/sleep.h>

#include "drivers/gpio.h"
#include "drivers/timer.h"
#include "drivers/clock.h"
#include "drivers/led.h"
#include "drivers/mux.h"
#include "drivers/uart.h"
#include "drivers/adc.h"
#include "drivers/int.h"
#include "drivers/sd.h"
#include "drivers/pot.h"
#include "drivers/dma.h"
#include "drivers/spi.h"
#include "drivers/reset.h"
#include "drivers/eeprom.h"
#include "drivers/sram.h"
